# Machine Learning

1. Machine Learning is making the computer learn form data and statistics
2. Machine Learning is a step to go into the direction of Artificial Intelligence (AI)
3. Machine Learning is program that anlysis data and learn from data to predict the outcome. 

## Dataset

1. Dataset is any collection of data (information)
2. Machine Learning use Big Data for prediction 
3. To analyze data, it is important to know that what types of data we are dealing with.
4. There are different types of Data:
    1. Numerical
    2. Categorical
    3. Ordinal

### 1. Numerical Data:
    1. Numerical data are numbers
    2. There are two differnt types of numerical data:
        1. Discrete:
            1. Numbers that are limited to integers Example Number of cars passing by
        2. Contineous:
            2. Numbers that are infinite value Example Price of an item, (Petrol), size of an item

### 2. Categorical Data:
    1. Data are values that can be measured up against each other Example colors or yes or No , True or False, spam or not spam

3. Ordinal:
    1. Ordinal data are like categorical data, but can be measured up against
    2. Example:
        1. School grades where A is better than B and so on.

## 1. Mean, Median, Mode Values

**1. What can we learn from group of Numburs?**

1. There are three types of values in Machine Learning use:
    1. Mean - Average Value
    2. Median - The mid point value
    3. Mode - most common value

**Example - We have registered speed of cars [13], What is the average value, middle, most common speed?**  

In [1]:
speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]

#### 1. Mean:
    1. The mean value is the average value
    2. Calculate mean, find the sum of all values, and divide sum by the numbers of values

In [3]:
(99 + 86 + 87 + 88 + 111 + 86 + 103 + 87 + 94 + 78 + 77 + 85 + 86) / 13

89.76923076923077

In [5]:
speed = (99 + 86 + 87 + 88 + 111 + 86 + 103 + 87 + 94 + 78 + 77 + 85 + 86)

average_value = speed /13
print(average_value)

89.76923076923077


In [7]:
import numpy as np

speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]

x = np.mean(speed)
print(x)

89.76923076923077


### 2. Median

In [8]:
import numpy as np
speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]

my_result = np.sort(speed)
print(my_result)

[ 77  78  85  86  86  86  87  87  88  94  99 103 111]


In [11]:
x = np.median(my_result)
print(x)

87.0


In [14]:
import numpy as np
speed = [99,86,87,88,111,86,87,94,75, 78,85,86]

my_result = np.sort(speed)
print(my_result)

[ 75  78  85  86  86  86  87  87  88  94  99 111]


**If there are two numbers in the middle, divide the sum of numbers by two**

In [15]:
(86 + 87) /2

86.5

In [16]:
x = np.median(my_result)
print(x)

86.5


## 3. Mode

1. The mode value is the value that appears the most number of times

In [19]:
import numpy as np
from scipy import stats
speed = [99,86,87,88,111,86,87,94,75,78,85,86]

my_result = np.sort(speed)
print(my_result)

[ 75  78  85  86  86  86  87  87  88  94  99 111]


In [20]:
x = stats.mode(speed)
print(x)

ModeResult(mode=array([86]), count=array([3]))
