## 2. Negative Indexing

### 1. 1-D Arrays

In [2]:
import numpy as np
my_array = np.array([10,20,30,40,50,60])
print(my_array[-1])


60


### 2. 2-D Arrays

In [3]:
my_array = np.array([[10,20,30],[40,50,60]])
print(my_array[-2,1])

20


### 3. 3-D Arrays

In [5]:
my_array =  np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])

In [6]:
print(my_array[-1,0,1])

80


In [7]:
print(my_array[-1,-1,-2])

110


In [9]:
print(my_array[-1,-2,-2])

80


In [12]:
print(my_array)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]


In [13]:
my_array =  np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]],[[130,140,150],[160,170,180]]])

In [14]:
print(my_array)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]

 [[130 140 150]
  [160 170 180]]]


In [20]:
print(my_array[-1,-1,-3])
print(my_array[-2,-1,-3])
print(my_array[-3,-1,-3])

160
100
40


## 3. Slicing Element access using Slicing

### 1. 1-D Arrays

In [23]:
my_array = np.array([10,20,30,40,50,60,70,80,90])
print(my_array[1:6])

[20 30 40 50 60]


In [24]:
my_array = np.array([10,20,30,40,50,60,70,80,90])
print(my_array[1:])

[20 30 40 50 60 70 80 90]


In [25]:
my_array = np.array([10,20,30,40,50,60,70,80,90])
print(my_array[:8])

[10 20 30 40 50 60 70 80]


In [26]:
my_array = np.array([10,20,30,40,50,60,70,80,90])
print(my_array[:])

[10 20 30 40 50 60 70 80 90]


### 2. 2-D Arrays

In [27]:
my_array = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(my_array[0,:])

[10 20 30 40 50]


In [29]:
my_array = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(my_array[1,:])

[ 60  70  80  90 100]


In [30]:
my_array = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(my_array[0,1:])

[20 30 40 50]


In [31]:
my_array = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(my_array[1,:4])

[60 70 80 90]


### 3. 3-D Arrays

In [34]:
my_array =  np.array([[[10,20,30,11,12,13],[40,50,60,14,15,16]],
                      [[70,80,90,71,81,91],[100,110,120,101,111,112]],
                      [[130,140,150,141,151,161],[160,170,180,171,181,191]]])

print(my_array[1,])

[[ 70  80  90  71  81  91]
 [100 110 120 101 111 112]]


In [37]:
my_array =  np.array([[[10,20,30,11,12,13],[40,50,60,14,15,16]],
                      [[70,80,90,71,81,91],[100,110,120,101,111,112]],
                      [[130,140,150,141,151,161],[160,170,180,171,181,191]]])

print(my_array[1,:])

[[ 70  80  90  71  81  91]
 [100 110 120 101 111 112]]


In [38]:
my_array =  np.array([[[10,20,30,11,12,13],[40,50,60,14,15,16]],
                      [[70,80,90,71,81,91],[100,110,120,101,111,112]],
                      [[130,140,150,141,151,161],[160,170,180,171,181,191]]])

print(my_array[1,1,:])

[100 110 120 101 111 112]


In [39]:
my_array =  np.array([[[10,20,30,11,12,13],[40,50,60,14,15,16]],
                      [[70,80,90,71,81,91],[100,110,120,101,111,112]],
                      [[130,140,150,141,151,161],[160,170,180,171,181,191]]])

print(my_array[1,1,1:4])

[110 120 101]


# 4. Steps [Slicing]

### 1. 1-D Arrays

In [41]:
my_array = np.array([10,20,30,40,50,60,70,80,90])
print(my_array[0::2])

[10 30 50 70 90]


In [42]:
my_array = np.array([10,20,30,40,50,60,70,80,90])
print(my_array[0::3])

[10 40 70]


### 2. 2-D Arrays

In [43]:
my_array = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(my_array[0,0::2])

[10 30 50]


In [44]:
my_array = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(my_array[0,0::1])

[10 20 30 40 50]


In [45]:
my_array = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(my_array[1,0::3])

[60 90]


### 3. 3-D Arrays

In [47]:
my_array =  np.array([[[10,20,30,11,12,13],[40,50,60,14,15,16]],
                      [[70,80,90,71,81,91],[100,110,120,101,111,112]],
                      [[130,140,150,141,151,161],[160,170,180,171,181,191]]])

print(my_array[2,1,0::2])

[160 180 181]


In [48]:
my_array =  np.array([[[10,20,30,11,12,13],[40,50,60,14,15,16]],
                      [[70,80,90,71,81,91],[100,110,120,101,111,112]],
                      [[130,140,150,141,151,161],[160,170,180,171,181,191]]])

print(my_array[2,1,0:4:2])

[160 180]


# Data Types of Python

1. Strings - It is used to represent text data, text represent in quatation marks Example: "Hello World..!"
2. Integer - It is used to represent integer number Example: 10,20,30,40 etc.
3. Float - It is used to represent real Number Example: 10.10,20.20 etc.
4. Complex - It is used to represent complex number Example: 1.0+j etc.
5. Boolean - It is used to represent True or False

# Data Types in Numpy:
    1. Numpy has some extra data types, and refers to the only single character like, i for integer

1. i - integer
2. b - boolean
3. u - unsigned integer
4. f - float
5. c - complex float
6. M - timedelta
7. O - object
8. S - String
9. U - Unicode String
10. V - Fixed chunks of memory for other types (void)